# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

# Override the EXPOSE instruction from the parent image and change the port to 8080
EXPOSE 8080

# Include the io.openshift.expose-service label to indicate the changed port that the web server runs on
LABEL io.openshift.expose-services="8080:http"

# Update the list of labels 
LABEL io.k8s.description="A basic Apache HTTP Server child image, uses ONBUILD" \
      io.k8s.display-name="Apache HTTP Server" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="apache, httpd"

# run the web server on an unprivileged port
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf \
RUN sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" \
    /etc/httpd/conf/httpd.conf

# Change the group ID and permissions of the folders where the web server process reads and writes files
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd


# Add a USER instruction for an unprivileged user. The Red Hat convention is to use userid 1001
USER 1001

